# 🛰 工位总览 · 6 路同屏 + 手动控制机器人 (2026-09-27, v5.15.15 → v5.15.16)

老倪需求原文:
> 「三个摄像头的图像，要同时显示，还有深度图，加上工控机 OPT 相机 金手指检测和表面检测，
>   就是 6 个窗口同时显示；窗口要留出控制区，可以控制机器人 X Y Z 平动以及绕轴旋转的 A B C 操作，
>   这样我就可以手动控制机器人了」

---

## 0. 第二轮修复 (老倪反馈: 「10082/10083 没有图像；控制区前进后退等按钮无法操作」)

三个真根因, 都实测到证据后才改:

**① 控制区按钮"点不动" = 浏览器连接名额被占满 (不是按钮坏了)**
`ss -tnp` 实测老倪那个 chromium 进程对 `8791` 恰为 **6 条连接**(HTTP/1.1 对同一 host:port 上限),
之前 6 格里有 2 格是长连接 MJPEG, 加上状态/快照请求 ⇒ 满格; 按钮的 POST 一直排在队里,
表现就是"点了没反应/按钮灰着"。修法:
  · 总览页 **一格 MJPEG 都不用**: 6 格全走**串行单帧快照**(全局一次只发一条请求) ⇒ 常占 1 条;
  · 总览页挪到**自己的端口 8793**(`--station-port`), 主端口 `/station` 一律 **302** 过去 ⇒
    与其它本机页面(叠加页/画布)**各占各的 6 条名额**, 互不饿死;
  · 按钮加 15s 兜底放开 + 请求超时(18s)后明写"请求没发出去/超时", 不再无声无息。

**② 金手指 10082 "没有图像" = 工控机内存里当时没有照片**
实测 `GET /picture?kind=origin` 在它闲着的时侯返
`404 {"code":404,"msg":"尚无照片: 先 POST /capture_detect 或 GET /picture?grab=1"}` ——
OPT 只在检测/拍照时留图, 我们只 GET 不拍照 ⇒ 取了个空。修法:
  · 面板按这句话(**不猜**): 明写"工控机内存里当前没有照片", 并给 **📸 拍一帧**
    (走 `GET /picture?kind=origin&grab=1`, 实测 HTTP 200 / 4.9MB / 1.4s) ;
  · **🔁 自动取景**(默认开, 页面上可关): 发现 404 就替它现拍一张, 最快 30s 一次;
  · 判据图之外再存一张 **整板原图**(2048×2448 → 缩到 1400×1171), 面板上「判据图(一条区域) /
    整板原图」一键切换 —— 之前只有一条区域的判据图, 看着像"没图";
  · 拍过之后 90s 内即使 OPT 又没照片, 面板也按**在线**报(画面确实是新拍的), 不写"取图失败"
    把好图说成坏的。

**③ 表面检测 10083 "没有图像" = 那台服务根本没有取图路由(本机侧无解)**
实测 10083 的 `/picture`、`/image`、`/last_result` 等 GET 全 404, 只有 `POST /capture_detect`
(`{"success":true}` = 只受理不带图)。所以这一格如实写"该路没有取图路由"+ 给「📸 拍帧」;
要真画面必须在工控机上加一条取图路由, 补丁: `docs/patch/opt_surface_10083_add_picture_route.md`。

**验证口径(离屏真跑, 不猜)**
  · 页面/端口: `8791/station` → 302 → `8793/station` 200 (19150B, 6 个 `data-mode="snap"`, 0 个 `.mjpg`);
  · 同浏览器里叠加页(3 条 MJPEG)开着时, 总览页仍在刷: 11s 内 5 格 `src` 全部推进、状态帧龄 0.01s、
    看门狗未报警 (`ss` 实测 8791/8793 各占各的);
  · 按钮端到端: 点「⏩前进」→ 页面出执行器原始三行 `Δ=(+10.0,+0.0,+0.0)mm → DRY-RUN /move_line`;
    点「↺+C」→ `🔄 绕C(工具Z·自转) +5.0°: 当前位置不动, 姿态 quat […]→[…] → /move_pose`(演练);
  · 自动取景分支: `tools/verify_aoi_autograb_branch.py`(假 404 → 断言补发 grab=1 且两路帧槽落地) **PASS**;
  · 桌面取证图: `/tmp/station_6panel_v3.png` (3840×2086, 5 格有内容 std 73~104, 第 6 格是那路无路由的面板)。

**踩坑(已写进技能)**
  · `pkill -f cam_live_stream.py` 连**同一条命令行里出现的文件名**都会匹配到 ⇒ 把自己的命令 SIGTERM;
    改成**按端口找 pid**(`ss -tlnp | grep :8791`)再 kill。
  · MJPEG 页面**永远不触发浏览器 load 事件**, 自动化浏览器 `navigate` 会超时(页面其实已加载)⇒
    取证改成读 DOM。

---

## 0.5 第三轮 (老倪: 「10083通道还是没有信号；控制区域不好用；修」)

### A. 10083 表面相机 "没有信号" —— 已穷举到不能再穷举, **结论: 本机侧无解, 必须动工控机**
不是"没试", 是三条路都试到底了(全部零副作用/只读):
| 试法 | 结果 |
|---|---|
| 10083 上 **55 条候选路径** 逐个 `OPTIONS`(含 /picture /image /snapshot /stream /static /surface_images /拼音名…) | **只有 `/capture_detect` (Allow: POST, OPTIONS)**, 其余全 404 |
| 工控机**其它端口**(1~65535 全扫 + 常用 web 口) | 没有第二个 HTTP 服务; 10081 的 /picture 也 404 |
| 文件共享取它落盘的 `./surface_images/` | 445/139 开着, 但 `smbclient -N` = `NT_STATUS_ACCESS_DENIED`(无匿名共享, 本机也没有那台机器的凭据) |
⇒ 工控机那套程序**根本没实现取图口**。唯一修法 = 上补丁 `docs/patch/opt_surface_10083_add_picture_route.md`
(约 30 行 + 现场 4 步自测)。**补丁一上, 本页不用改一行就会自动出图** —— 这一格一直按 0.25Hz 轮询
`GET /picture?kind=origin`, 一有 200 立刻显示真图。面板现在把这条证据和文件路径直接写在画面上(不猜、不编)。
工具: `tools/probe_aoi_routes.py`(单端口穷举) · `tools/probe_10083_deep.py`(深挖+端口清点) ·
`tools/sweep_opt_host_ports.py`(全端口扫描)。

### B. 控制区重做 (老倪: 「不好用」)
| 毛病 | 现在 |
|---|---|
| 6 个方向按钮排两列, 又要滚屏才能看到授权/结果 | **十字 D-pad**(3×3, 按钮 92px 高, 中央显示当前步长) + **键盘**: ↑↓←→ = 前后左右 · PgUp/PgDn = 升降 · A/B/C(+Shift 反向) = 绕轴旋转 |
| 「授权真动」是个小勾选框, 每次都要找 | **顶部一个大开关**(⛔演练模式 ↔ ✅真动已启用), 绿色/黄色大字, 状态记在 localStorage(刷新不丢) |
| 按钮点了不知道有没有下发 | 按钮 0.9s 闪光 + 「下发中…(最多等 15s)」+ 结果带**本次用时**(如 `用时 1.2s`)+ 原始日志 + 「📄 复制原始日志」按钮 |
| 「点了没动」分不清是没下发还是动作慢 | 结果行明写「**对上 X/Y/Z 看有没有变就知道动没动**」; 状态条加 **🔄 移动中** 标记(operation_state≠idle) |
| 速度语义不清, 8 很慢还会报一次超时 | 速度预设 `8 慢·默认 / 20 / 40 / 60 快` + 明写: 8 很慢(可能十几~几十秒), 停下前驱动会报一次
`wait_until_idle` 超时 —— **那是超时标记不是失败**(已实测: 动作真跑了, 只是等待窗口 30s) |
| 布局: 6 格挤占整屏, 控制列要滚动 | `main` 改 2 列(左 6 格 / 右 640px 控制列各自独立滚动), 窄屏自动堆叠(手机可用) |

实测(离屏真跑): 点「⏩前进」→ `Δ=(+10.0,+0.0,+0.0)mm → DRY-RUN /move_line`, 页面回 `🧪 演练(未下发) · 用时 1.2s`;
按 **Shift+A** → `🔄 绕A(工具X·俯仰) -5.0°: 当前位置不动, 姿态 quat [−0.0918 −0.6938 0.7062 0.1071] → … → /move_pose`;
步长切到 50 → D-pad 中央与六个按钮的提示同步变 `50mm`; 取图仍是 6 格串行单帧快照(0 个 .mjpg), 他那个浏览器对 8793 只占 2 条连接。
取证图: `/tmp/station_console_v3.png`(3840×2086, 控制列 std 86 有内容) / 缩图 `/tmp/station_console_v3.jpg`。

**顺带记一条现场实况**: 三查里 `ROBOT_IDLE_TIMEOUT` 是**我们桥**在 08:23 那次 /move_line 等 idle
30s 记的标记(`controller_error_logs` 为空 = 控制器侧无报警), 与 v5.7.0 记录的驱动行为一致:
**判动作完成要看 TCP/operation_state, 不能凭 success=False 重发**(重发会叠加第二次动作)。页面已把来源写明。

---

## 0.6 第四轮 (老倪: 「更新工控机的表面检测程序，升级到v4版本；程序路径 D:\xspace\ultralytics_AOI；
##      cam_surface_10083_work_v2.py；不要改v2；通道还是10083」)

### A. 交付件 (v4 早就写好并离线验过, 这轮把它送到那台机器上)
| 文件 | 说明 |
|---|---|
| `surface_10083_work_v4.py` (20725B, 488 行) | 独立文件, **不覆盖/不改 v2 任何文件**; 端口默认 **10083**; 复用 v2 同目录的 SciCam SDK / yolo_detector / config.yaml |
| `upgrade_10083_v4.ps1` | 上线脚本: `-CheckOnly` 只自检 / 不带参 = 起 10084 试跑(不碰 v2) / `-Apply` = 停 v2→起 v4→真拍一张验图 |
| `README_上线步骤.txt` | 三步操作 + 验收判据 + 回滚(10 秒) + 相机独占注意事项 |
| `surface_10083_work_v4.py.sha256` | `65b5a1a6…f8e42`(脚本会核对) |
| 下载地址 | **`http://192.168.23.50:8794/`** (4060 本机 8794 静态文件服务, 工控机同网段直连; 本机路由实测 `dev enx00e04c0c32a0 src 192.168.23.50`; 本机防火墙 inactive) |

v4 相对 v2 = **只加不减**: `POST /capture_detect` 回执逐字一致(`{"code":200,"msg":"success"}` —— 已实测 v2 现场回执就是这个);
新增 `GET /picture?kind=crop|origin[&meta=1][&grab=1]`、`GET /last_result`、`GET /crop_info`;
相机常驻 + 单 worker 异步队列; 规范图 = `config.yaml` housing 的 `imgsz=1280` 保比例 letterbox(表面全幅检测不拉伸)。
离线契约测试(`aoi_v4/.venv-test` + `_stub` 假相机/假检测器)实测 5/5 通过:
`capture_detect 200` / `picture?kind=crop 200 1280×1280` / `picture?kind=origin 200 2048×2448` /
`last_result 200 {verdict:NG,count:2,ms:12.3}` / `crop_info 200 {canonical:[1280,1280],mean:68.1}`。

### B. 本页(工位总览)配合改动 —— 上完 v4 **本页零改动就出图**
· 表面 worker 取图口径改 `kind=crop`(模型真正看到的那张规范图, 也是判决依据); 金手指仍 `kind=origin`→去死白判据图。
· 表面也读 `/last_result` → 那一格的标题栏会带上「上轮判定 OK/NG (n 缺陷 · 推理 xxms)」(与本页给金手指的待遇一致)。
· 「📸 拍帧」补了**拍后取图**: v4 的 `/capture_detect` 回执不带图, 拍完顺手 GET 一次 `/picture` 把图取回来
  (只读取图, 不会再拍); v2 下这条 GET 仍 404 → 行为与升级前一致。
· 面板文案改成现状: 「10083 那台程序还是 v2(没有取图路由)」+ **怎么上 v4**(文件名/目标目录/端口不变/v2 不改) +
  「它一上线本页不用改一行就出图」。55 条候选路径全 404 的实测结论保留在文案里(留证据, 不是搪塞)。
· 实测(重启后): `10083 → HTTP 404 (kind=crop)` 如实记在 `/station/status` 的 `aoi['10083']` 里,
  `aoi_surface` 帧槽 `online:false`; 10082 仍 `ok:true · 4799KB/帧`。取证图 `/tmp/station_v4patch.png`。

---

## 0.7 第五轮 (老倪: 「金手指和表面检测的窗口要改成实时推流；不检测的时候不用保存那么多图片；
##      升级工控机的程序到 v5，不要改变服务通道；控制台还是无法操作前进后退」)

### A. 控制台"无法操作"的真正根因 —— **页面的「授权真动」没开**(有日志为证)
执行器日志里他两次点击都是 `DRY-RUN(未下发)`：
```
[08:52:39] 目标 L2.left: Δ=(+0.0, +10.0, +0.0)mm →向左(+Y) · 位姿来源 direct
[08:52:39] DRY-RUN L2.left → timeout 90 ros2 service call /move_line …      ← 没真下发
[08:52:43] 目标 L2.forward: Δ=(+10.0, +0.0, +0.0)mm →前进(+X)
[08:52:43] DRY-RUN L2.forward → …
```
即**链路本身是通的**，只是页面 `arm:0`（演练）。修法（v5.15.17 → 本轮）：
· **默认就是真动**(页面加载即 ARMED=true, 红/绿大字条明示, 仍可一键切演练)；
· 演练模式下点了动作 → 结果行直接给一个「▶ 立刻真动执行一次」按钮(不用再去找开关)；
· 速度上限从 30 放到 60(与页面档位一致)；按钮闪光 + 「下发中…」+ 本次用时 + 执行器原始三行 + 一键复制。
**真实链路端到端实测**(不是空跑)：
```
真动前 TCP X 0.3910 → POST /ctl/move {L2.forward, d_mm=10, speed=20, arm=1} → 1.6s 回"已下发"
  日志: [09:03:37] 已下发 L2.forward -> 10.0 · Δ=(+10.0,+0.0,+0.0)mm →前进(+X)
真动后 TCP X 0.4010   ⇒ 真的走了 +10.0mm
再从**页面按钮**点「⏪后退」把臂走回原位: [09:08:01] 已下发 L2.backward → 09:08:09 ROS response
  TCP X 0.4010 → 0.3910   ⇒ 页面→执行器→ROS→机械臂 全链路通
```
(/move_line /move_pose 服务实测在线, /robot/tcp_pose 32~38Hz。)

### B. 金手指 / 表面 两格改 **实时推流(MJPEG)**
· 服务端本来就有通用 MJPEG 路由 ⇒ 直接给这两格用：`/aoi_gold.mjpg`、`/aoi_surface.mjpg`(推的是**加工后的
  判据图/规范图**, 不是原始 4.9MB PNG)。测试: 5s 抓流 = 767KB/6 分片 ≈1.2fps。
· 取图频率 0.25Hz → **1.0Hz**(老倪要"实时")；金手指那格仍 4.9MB/帧(源侧 origin 54ms 就给)，
  表面取 v4/v5 的 `kind=crop`(模型看的那张)。
· 连接名额算清楚了: 2 条 MJPEG + 1 条状态轮询 + 1 条串行快照 = **≤4 条**(本机上限 6) —— 这是"能推流又不
  把按钮饿死"的前提, 4 个真实相机格继续走单帧快照就是这个原因。
· 面板标题加「🔴 实时推流」标记; 「判据图/整板原图」切换改成换 MJPEG 源。
· 副作用记录: `<img>` 挂 MJPEG 长连接后浏览器**永不触发 onload**, `browser_navigate` 那种"等加载完成"的
  自动化会超时 —— 取证改用 console/DOM 查询(本轮就是这么做的)。

### C. v5 (两路) —— 不检测时不再堆图
`GET /picture?grab=1`(**只看一眼 / 页面的「拍帧」**) → 图只留内存, **不落盘**；
`POST /capture_detect`(真检测) → 照旧落盘(模型要读文件), 落完按上限清旧图；
诊断图(标注/legacy)默认不写(`AOI_SAVE_DEBUG=1` 才写)；取图优先走内存(不再读盘)；
新增 `GET /storage`、`POST /prune`；端口/路由/回执语义全不变。
离线契约(桩相机+桩检测器, 真跑 GrabAndSaveImage)实测 **两路各 5/5 通过**:
① 真检测 200 且落盘 2 张 · ② `grab=1` 200 有图且磁盘 2→2 张(**不增**) ·
③ 把磁盘清空后 `grab=1` 仍 200(内存帧, 表面 65529B / 金手指 18674B) ·
④ `/storage` + `POST /prune` 正常 · ⑤ `&save=1` 才写盘。
上线包 `http://192.168.23.50:8794/v5/`(旧 v4 包 URL 仍可用)：两程序 + `upgrade_aoi_v5.ps1`(自检/试跑
10084·10085/正式升级) + README + sha256。**等老倪统一换服务**(我不动他的手)。

---

## 0.8 第六轮 (老倪: 「页面的『授权真动』 / 现场安全 / 授权」)

**纠回上一版的方向**: 上一轮为了让"点了不动作"不再发生, 把页面改成**默认就是真动** ——
老倪当轮就纠回: **现场安全优先, 默认必须未授权; 真动要授权**。两边都满足的最终设计:

### A. 授权流程 (页面, 两段式, 不记忆)
· **默认未授权**(琥珀色横条「⛔ 未授权 · 点方向键只会算目标, 机械臂不会动」), 刷新/换人/重连一律回到未授权;
· 授权 = **两步**: 点「🔓 授权真动」→ 按钮变「⚠️ 再点一次: 现场确认无人」(6s 内不作废) → 再点才成立;
· 授权成立: 横条转绿「✅ 真动已授权 · 剩 4分58秒后自动失效 · 授权IP 127.0.0.1」, 按钮变「🔒 立即撤销授权」;
· **授权有时限**: 默认 300s(`--ctl-auth-window`), 到期自动回未授权并在结果行提示「⌛ 授权已到期…」;
· 撤销**永远允许**(撤销不需要授权 —— 安全方向), 点一下立即失效;
· 未授权时方向键调淡(opacity .55)但仍可点 —— **点了必出结果**: 「🧪 演练(未下发): 未授权真动(只算目标,
  不下发) · 用时 1.6s」+ 执行器原始行 + 旁边一个「🔓 授权真动(现场确认无人)」入口按钮。

### B. 闸门在**服务端**强制(页面上那套只是镜像, 不是样子货)
`POST /ctl/arm {on:true|false}`(只有 POST) · `_auth_set()` 记 IP+时刻+note 进 `/tmp/zmax_ctl.log`(与动作同一时间线);
`/ctl/move` 带 `arm=1` 时校验授权窗口, 过期/未授权 → **HTTP 403**(不是 200+JSON):
```
未授权:  POST /ctl/move {"skill":"L2.forward","d_mm":10,"speed":20,"arm":1}
         → HTTP 403 {"ok":false,"denied":true,"code":403,"auth":{"armed":false,…},
                     "msg":"未授权真动(现场安全): 先点页面上『🔓 授权真动』并二次确认…"}
         → TCP X 0.3910 一字未动
授权后:  页面两步授权 → armed=true ip=127.0.0.1 left=300s
         页面点「⏩前进」→ ✅ 已下发(真动) 1.2s → TCP X 0.3910→0.4010 (+10.0mm)
         页面点「⏪后退」→ ✅ 已下发(真动) → TCP X 0.4010→0.3910 (回原位)
撤销后:  armed=false → 再点前进 → HTTP 403 (拒绝)
审计:    09:18:55 auth=False 页面撤销 · 09:18:59 auth=True 页面两步确认(现场安全)
         09:19:03 动作 L2.forward dry=False · 09:19:38 动作 L2.backward dry=False · 09:19:38 auth=False 页面撤销
```
`_send` 也改成真发 `out["code"]` 的状态码(原来把 403 写进 JSON 却发 HTTP 200 —— 上层/监控看不到拒绝)。
本仓除本页外**没有别的自动调用方**打 `/ctl/move`(已 grep), 所以收紧不会破坏既有链路。

### C. 与上一轮的关系(别把两件事搞反)
「点了不动作」的**根因是没授权**, 不是链路坏; 所以修法是 **把授权变得显式、可见、两步、有时限**,
而不是把授权默认打开。授权状态在页面上永远可见(横条 + 🛡安全卡「🔐 真动授权: …」)。

---

## 0.9 第七轮 (v5 已上线工控机 + 反向通道 + 群消息降噪)

老倪: 「本地磁盘没用的数据可以删掉」+ 通道 `Test-NetConnection 192.168.23.50 -Port 8794` = True。

**A. 反向通道 (工控机 192.168.23.23 没有可登录端口)**
- 那台机器只开 135/139/445/10081/10082/10083, 22/3389/5985 全闭 ⇒ 从 4060 侧无法登录。
- 做法: `tools/agent_hub.py` (4060:8794) + Windows 端 12 行 `agent_start_ascii.ps1` (纯 ASCII, 避开 PS5.1 中文乱码)。
  老倪在工控机贴一行 → 每 3s 来取命令、跑完把输出 POST 回来。命令队列**只有 4060 本机可写** (网络侧只能取不能投), 带 token, 关窗即断。
- 通道实测: `CHANNEL OK -> {"ok": true, ...}` 后 15 条命令全部往返成功 (含真拍/检测/起停服务)。
- **踩坑**: ①PS 5.1 的 `irm` 不带 `-UseBasicParsing` 会卡在代理/IE 初始化 (老倪第一遍就卡在这, 我这边看到 0 连接);
  ②`Write-Host` 的输出**不会**被 `2>&1|Out-String` 捕获 ⇒ 回传命令只用管道输出 (纯字符串/cmdlet)。

**B. v5 部署到 10082/10083 (通道不变)**
- 落地: `D:\xspace\ultralytics_AOI\{cam_finger_10082_work_v5.py, surface_10083_work_v5.py}`,
  SHA256 核对 4ACFC458..FF0EC951 (36746B) / 940449BA..4B6A8BD4 (27013B) **一致**; 本机 `venv\Scripts\python.exe` 3.10.1 (cv2 4.10.0 / flask 3.1.3 / numpy 1.26.4) py_compile 通过。
- 试跑 10084/10085 (不碰产线口): 金手指 `POST /capture_detect` → 200 `{"code":200,"msg":"success"}`, 真检测落盘 (CropNatural 1→2), 内存缓存 `crop_kb=53.8 / origin_kb=338.2` 就位;
  随后 `GET /picture?kind=origin&grab=1` → **200 / 346361B, 磁盘张数不变** ✓。
  表面 10085: `grab=1` → 200 / 277871B ✓; `POST /capture_detect` 在该口返回 400「未配置检测模型, 可选端口 ['10083']」= **端口绑定的模型映射, 属设计** (所以正式口才验真检测)。
- 正式口验收 (从 4060 直连 192.168.23.23): 
  - 10082 `/last_result` → 200 `detect_type=gf, ms=1571, origin=./goldfinger_images/Finger_Image_W2448_H2048_No_1.png, saved_incoming=D:\AOI_images\gf\incoming\20260927_095433_001.png`
  - 10083 `/last_result` → 200 `detect_type=housing, ms=8852.6` (表检较重, 8.9s)
  - `POST /capture_detect` 两路均 200 success (回执语义一字未改); 10083 落盘 1→2 ✓
  - `GET /picture?kind=origin&grab=1`: 10082 385475B/0.73s, 10083 261485B/0.32s, 两路 **files_total 均不变** ✓
  - 总览两格 `/aoi_gold.mjpg` `/aoi_surface.mjpg` → 200 有流 ✓ (面板显 🔴 实时推流)
- 启动方式: 用 `WScript.Shell.Run(cmd,0,$false)` **分离启动** (不受那个 PowerShell 窗口关闭影响); 日志 `D:\xspace\ultralytics_AOI\v5[fs].log`。
  10081 上的原服务 pid 22328 全程未动 ✓。

**C. 群消息降噪 (老倪: 「没请求的时候不要总发图片, 不要刷屏」)**
- 查明噪声源: ①链路巡检 (每 30min 无条件 `✅ 链路正常` = 48 条/天) ②磁盘红线 (每 2h 打一屏过程提示) ③L4 进度任务 (每 30min 回「无变化」两字, 照样被投递) ④`tools/aoi_feishu_push.py --watch` (root 起的常驻, 有新图就推)。
- 处置: ①②改「正常就一个字都不打」(实测输出 0 字节) ③提示词改「没新东西只回 `[SILENT]`」④停掉 watcher (以后 `--once` 按需推)。
  磁盘超红线才报, 且**同一状态 6 小时只报一次** (实测第一次 702B / 第二次 0B)。

**D. 磁盘回收 (306G → 283G, 回到 300G 红线内)**
- 删: 重复 state dump 1.8G (硬链接同一份) / 8 月旧归档 0.48G / 重复的 Qwen2.5-VL-3B 副本 7.0G (`zmax_data/hf_home`, 默认 `~/.cache` 那份保留) / `l5_gen_v2+v3.h5` 12.8G / 无引用的 `smolvla_lew_v10_full` 1.4G / pip 缓存。
- 未删 (留证/留用): `optical_insert_v6_disturb_part00~04.npz` 4.3G (9-26 刚生成) / 09-21~22 真机录像 / 仍被配置或 GUI 引用的 smolvla 跑次。

## 0.10 第八轮 (老倪: 「以后你得自主更新工控机的程序，你是主节点，要完全控制工控机和 Orin；不要用 10084 10085 通道；还得用 10082 10083 通道」)

**A. 工控机侧改成"自治" (不再依赖老倪贴那一行 / 不再依赖某个窗口)**
- 两个 Windows 计划任务 (SYSTEM, 最高权限):
  - `ZMAX_Agent` (`/sc onstart`) → 跑 `zmax_agent_loop.ps1` → 反向通道轮询, 崩了 10s 后自拉起 ⇒ **我随时能驱动那台机器**。
  - `ZMAX_AOI_KeepAlive` (`/sc minute /mo 1`) → `zmax_keepalive.ps1`: 检查 10082/10083, **哪一个没在听就把它拉起来** (只在自己动手时写日志, 平时不输出)。
- **自愈实测**: 故意 kill 表面 v5 (pid 21764) → `schtasks /run /tn ZMAX_AOI_KeepAlive` → 25s 后 10083 起来; 日志 `2026-09-27 09:57:38 started: surface`。
  ⇒ 顺带证明 **相机 SDK 在 session 0(SYSTEM) 下能正常开相机**, 所以开机/无人登录也能起服务。
- 服务仍按 v5 的老口径启动: `cd /d D:\xspace\ultralytics_AOI && venv\Scripts\python.exe <脚本>` + 分离启动(`WScript.Shell.Run(...,0,$false)`)。

**B. 自主更新器 `tools/aoi_remote_deploy.py` (只用 10082/10083, 不碰 10084/10085)**
```
./gui-venv311/bin/python tools/aoi_remote_deploy.py --finger <金手指.py> --surface <表面.py>
# ①拷进 8794 静态目录 ②反向通道让工控机 iwr 下载 + Get-FileHash 与本地 SHA256 逐位核对(不一致就中止)
# ③现役程序备份成 .bak ④停旧起新(始终 10082/10083, 分离启动) ⑤验收 ⑥失败自动用 .bak 回滚并复验
```
- 验收项(缺一即失败): `/storage` 200 · `POST /capture_detect` 回执 `code=200` · `/last_result` 判决通道 · `grab=1` 出图字节>0 · **`grab=1` 前后 `files_total` 不增**(v5 不落盘口径)。
- **实测(幂等重发 v5)**: 10:02 一轮 6 项 **两路全过** —— 10082 `ms≈1557` / 10083 `ms≈8.9s`, `grab=1` 389377B / 273297B, `files_total` 4→4 与 2→2 不增 ✓。
- ⚠️ 踩坑: 第一版对 10083 只固定等 6s 就断言 `/last_result` 200 ⇒ **假失败并触发了回滚**(表面推理实测 ~8.9s)。
  已改成轮询最多 45s, 且接受 `/last_result` 的**两种合法形态**(`200+verdict/count` ‖ `404+尚无检测结果`)。

## 1. 交付物

**页面: `http://<本机IP>:8793/station`** (本机 `http://127.0.0.1:8793/station`;
主端口 `8791/station` 会 302 跳到这里 —— 8793 是总览专用端口, 独立 6 条连接名额)
入口: 「🧩 场景叠加」页头部有直达链接；8791 服务的启动日志里也打印 URL。

六格 (左 2×3 网格) + 右侧控制列:

| 格 | 源 | 取图方式 | 实测 |
|---|---|---|---|
| 🦾 机器人臂上 D405 | Orin `8792/frame.jpg` | 单帧快照 1s | 640×480 · 3~4fps · 帧龄 0.3~1.8s |
| 💻 笔记本内置 | 本机 `/dev/video2` | 单帧快照 0.4s | 640×480 · 源 15fps · 帧龄 0.01s |
| 📺 MAXHUB 顶摄 | 本机 `/dev/video0` | 单帧快照 0.4s | 1280×720 · 源 22~28fps · 帧龄 0.02s |
| 🌈 D405 深度图 | 容器只读订阅深度话题 → 伪彩 | 单帧快照 1.5s | 640×526(含 46px 真值带) · 源 0.24Hz · 有效 88% |
| 🔍 金手指检测 | 工控机 10082 `/picture?kind=origin` → 去死白判据图 | 单帧快照 3s | 900×900 判据图 · 源图 5.9MB/帧 · 0.24Hz |
| 🔍 表面检测 | 工控机 10083 | 无取图路由(见 §5) | 只能「拍帧」触发, 回执 `{"success":true}` 无图 |

右侧控制列: 三查状态 · TCP 位姿 · X Y Z 平动 6 按钮 · A B C 绕轴旋转 6 按钮 · 步长/角度/速度 · 授权闸门 · 点击结果(原始日志行, 可复制)

---

## 2. 链路与文件 (谁产出什么)

```
Orin 192.168.23.66
  /realsense/depth/image_rect_raw (16UC1 640x480 step=1280, 实测 0.24Hz)
  /realsense/color/image_raw     /robot/tcp_pose (50Hz)   /robot_status (JSON 字符串)
        │  容器 ss-remote-tap (ROS_DOMAIN_ID=0, 只读订阅)
        ├─ tools/ros_depth_stream.py  → zmax_scene/depth_raw.npy + depth_meta.json   (numpy, 无 cv2)
        └─ tools/ros_tcp_cache.py     → zmax_scene/tcp_pose.json + robot_status.json (20Hz 落盘)
        │  (宿主 /home/ubuntu/zmax/zmax_data/ss_live 挂的是容器 /out)
宿主 4060
  tools/depth_colorize.py          ← 彩色化口径**唯一真源**(容器/宿主共用, 不各写一份)
  tools/cam_live_stream.py (8791)
        ├─ _depth_worker       读 npy → 伪彩+真值带 → 帧槽 depth
        ├─ _aoi_worker(10082)  GET 取原图(不带 grab) → 去死白 → 帧槽 aoi_gold; 另读 /last_result
        ├─ _aoi_worker(10083)  实测 404 → 如实报"无取图路由", 不假装有画面
        ├─ _ctl_move/_ctl_status  POST /ctl/move · GET /station/status
        └─ 页面 /station (STATION_PAGE)
工控机 192.168.23.23
  10082 金手指 (Flask): GET /picture?kind=origin|natural|crop · /last_result · POST /capture_detect
  10083 表面  (Flask): 只有 POST /capture_detect
```

## 3. 手动控制 (X Y Z 平动 + A B C 绕轴旋转)

**平动**: 复用既有 6 个方向技能 `L2.forward/backward/left/right/lift/lower` (走 `/move_line`)。
**旋转**: 新加**执行算子** `pose_rot` (`tools/l2_daemon.py::build_pose_rot`) + 6 个技能
`L2.rot_{a,b,c}_{pos,neg}` (`tools/register_rot_skills.py` 注册, 现注册表共 54 个技能)。

| 轴 | 含义 | 数学 |
|---|---|---|
| A | 绕**工具 X 轴** 俯仰 | `q_new = q_cur · q_axis(θ)` |
| B | 绕**工具 Y 轴** 倾侧 | 同上, 右手定则, **工具系** |
| C | 绕**工具 Z 轴** 自转(画面原地转) | 同上 |

* 位置**不动**(实测日志 ΔX/ΔY/ΔZ = +0.0mm), 只改姿态; 走 `/move_pose` (与已验证的
  `tools/l2_pose_rot.py` 同一通道 —— 该通道实测不掉电, 免去反复上电解锁)。
* 度数只填正数, 方向由技能内定 (与方向点动同一口径, 现场不填负号)。
* 执行层守卫 `max_deg` 默认 10°(注册时写入, 页面给 1/5/10/20 步长, >30° 直接拒发)。

**四道闸门** (缺一不下发):

1. 服务级: `cam_live_stream.py --ctl-motion` (不加 ⇒ 一律 dry-run)
2. 页面级: 勾「授权真动」(不勾 ⇒ 请求仍打到服务, 但服务强制 dry)
3. 白名单: 只认上面 12 个技能; 其它技能(点位/多阶段/夹爪)一律拒 (`L2.goto_point` 实测被拒)
4. 限幅+限流: 平动 5~300mm(下降 ≤100)、旋转 1~30°、速度 1~30、真指令间隔 ≥1.5s(防连点当摇杆)

* **GET 一律不触发动作**(`GET /ctl/move` → 404): 浏览器预取/爬虫/取证脚本都会 GET, 不能让一次预取动臂。
* 每次点击**必须**返回执行器原始日志行(可复制), 不留"已发送"这种自报。样例:
  `[08:16:38] 目标 L2.backward: Δ=(-10.0,+0.0,+0.0)mm →后退(-X) · 位姿来源 direct` →
  `DRY-RUN L2.backward → ros2 service call /move_line ...` → `受理: DRY-RUN(未下发)`
* **没有软急停**: 不提供未验证的停止指令, 急停走示教器/现场急停按钮 (页面已写明)。

## 4. 实测取证 (2026-09-27 08:1x)

* 六格: 前 5 格的 `naturalWidth/Height` 实测 `640×480 / 640×480 / 1280×720 / 640×526 / 900×900`;
  表面格无帧(如实标注)。像素体检: std 69.7 / 68.3 / 56.8 / 55.7 / 66.0, 近黑占比 ≤7.9%(深度无效区)。
* `/station/status`: 三查 `power=on · operation=idle · has_error=false · estop=false · collision=false`(帧龄 0.26s);
  TCP `X 0.5337 Y 0.2313 Z 0.2271`(帧龄 0.04s); `motion_armed=true`。
* 金手指 `/last_result`: `count=0 · detect_type=gf · ms=1637 · n=246`(真检测结果, 不是编的)。
* 旋转空跑: `L2.rot_c_pos deg=5` → Δ=(0,0,0)mm · quat `[0.8114 0.0545 0.5814 -0.0250]` →
  `[0.8130 0.0191 0.5797 -0.0504]` · `/move_pose` 已受理(DRY-RUN 未下发)。
* 深度物理核对: `step=1280=640×2` 行主序 ✓; 有效 88%; 最近 0.196m / 中位 0.376m / 中心 0.444m;
  同一时刻深度 vs 彩色 **边缘相关 +0.05~+0.07**(正相关; 幅值小是 D405 深度未与 RGB 对齐的视差所致,
  传感器特性, 不是布局错 —— 布局若错会掉到 0 附近并出现花图)。
* 页面 JS 错误 0 条; 浏览器到 8791 的并发连接 **5 条**(≤6 上限)。

## 5. 已知边界 (如实, 未藏)

1. **10083 表面检测没有取图路由** → 那一格没有实时画面, 只有「📸 拍帧」按钮;
   实测 `POST /capture_detect` 返回 `{"success": true}`(200=受理) 且**回执里不带图**,
   所以点完也只有回执。要真正出图必须在工控机侧加一条取图路由
   (`docs/patch/opt_surface_10083_add_picture_route.md` 已备), 本机侧无解。
2. **臂上相机 3~4fps**: Orin load 7.7~10 时 `8792` 单帧要 1.8s; 帧龄如实标, 没藏。
3. **深度图 ~4s 一帧**: 源话题实测 0.24Hz(不是我们限的速), 页面上标的就是真帧龄。
4. **浏览器 HTTP/1.1 每主机 6 连接**: 6 格全用 MJPEG 会把连接占满 → 状态请求永远排队(页面卡"读取中…")。
   现方案: 高速两路留 MJPEG + 其余 4 格串行单帧快照 + 状态合并成 1 条请求 ⇒ 常占用 ≤5。
   页面自带卡顿自诊断提示(>7s 没更新就提示关掉其它 8791 页面)。
5. 服务**无鉴权**(局域网/产线网工具); 「授权真动」勾选后点击是真动臂 —— 现场请确认工作空间无人/无障碍。

## 6. 运维

```bash
# 起/重启 8791 (含 6 窗 + 手动控制; 真动授权只需去掉 --ctl-motion)
bash /home/ubuntu/.hermes/cache/scratch/restart_stream6.sh
# 执行器 (手动控制的下发口) 保活
bash /home/ubuntu/.hermes/scripts/l2_daemon_keepalive.sh
# 容器内两个常驻源 (深度 / 位姿+三查)
sudo docker exec -d ss-remote-tap bash -lc 'source /opt/ros/humble/setup.bash && export ROS_DOMAIN_ID=0 && \
  python3 /repo/tools/ros_depth_stream.py --hz 5'
sudo docker exec -d ss-remote-tap bash -lc 'source /opt/ros/humble/setup.bash && export ROS_DOMAIN_ID=0 && \
  python3 /repo/tools/ros_tcp_cache.py --hz 20'
```

坑 (都实打实踩过):

* `pkill -f "cam_live_stream.py"` 会**杀掉自己**(调用它的那条命令行里含同名字符串) → 用 `[c]am_...` 中括号技巧, 且别在同一条命令里再写全名。
* 容器(`ros:humble-ros-base`)**有 numpy 没 cv2**, 往里装重启即失 ⇒ 容器只落原始数组, 彩色化在宿主做。
* `aoi_exposure_fix.clean_judge_frame` 吃 **RGB**(内部按 RGB 加权算灰度), 喂 BGR 会判错 → 进出各转一次。
* ROS 头时间戳与宿主墙钟**不同源**(差~26h) ⇒ 帧龄只能取相对量(首帧对齐)。
